# Generated by Django 4.1.5 on 2023-01-28 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("models", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="user",
        ),
        migrations.CreateModel(
            name="VacanciesInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_request", models.BooleanField(default=False)),
                ("date_create", models.DateField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="models.vacancy"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="vacancy",
            name="user",
            field=models.ManyToManyField(
                through="models.VacanciesInfo", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
