# Generated by Django 4.1.5 on 2023-01-29 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0003_remove_vacancy_user_vacanciesinfo_vacancy_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="is_request",
        ),
    ]
